version: '2'
services:
  webmushra:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    user: "${UID}:${GID}"
    volumes:
      - ${WEBMUSHRA_RESULTS}:/var/www/html/data/results
      - ${WEBMUSHRA_CONFIGS}:/var/www/html/data/configs
    ports:
      - "30001:80"
    restart: unless-stopped
