testname: DialektDetect
testId: spatial
bufferSize: 2048
language: de
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php
pages:
    - type: generic
      id: welcome_page0
      name: <div style="font-size: 58px;"><b>Wilkommen bei DialektDetect!</b> </div>
      content: |
        <div style="font-size: 36px;"><b>
        Kannst du die richtigen Dialekte zuordnen?</b><br>
        Wenn du vorher noch etwas üben möchtest, klick auf diesen <a href="https://lorgu.github.io/dialekt-map/" target="_blank">Link</a>.</div>
    - type: consent
      id: consent_page
      name: Einverständniserklärung
      mustConsent: true
      content: |
        <p>In diesem Experiment hörst du kurze Sprachaufnahmen und sollst bestimmen, woher aus Österreich die sprechende Person kommt.
        Dafür klickst du auf die Karte und wählst einen Ort aus.<br>
        Außerdem wollen wir herausfinden, welche Teile von Dialektaufnahmen für dich besonders wichtig sind, um die Herkunft zu erkennen.<br>
        Die gesammelten Daten helfen uns zu erforschen, wie gut die Dialekte in Österreich erkannt werden.<br>
        Die Ergebnisse werden im Rahmen eines Forschungsprojekts anonymisiert ausgewertet und können in wissenschaftlichen Publikationen veröffentlicht werden.<br>
        Dein Name wird niemals öffentlich angezeigt oder weitergegeben.<br>
        Bei Fragen oder Problemen, schreibe eine Mail an <a href="mailto:lorenz.gutscher@ofai.at">lorenz.gutscher@ofai.at</a>.</p>
    - type: generic
      id: welcome_page2
      name: <div style="font-size: 48px;"><b>Dialekte in Österreich</b> </div>
      content: |
        <div style="font-size: 36px;">Österreichische Dialekte können sehr unterschiedlich sein.<br>
        Im Westen (Vorarlberg) wird <b>Alemannisch</b> gesprochen, östlich davon <b>Bairisch</b>.<br>
        In diesem Bild siehst du eine noch genauere Unterteilung in <b>6 Dialektgruppen</b>:<br> </div>
    - type: generic
      id: welcome_page1
      name: <div style="font-size: 38px;"><b>KI und Dialekt?</b> </div>
      content: |
        <div style="font-size: 28px;">
        Wir haben eine <b>Künstliche Intelligenz (KI)</b> darauf trainiert, Dialekte zu erkennen.<br>
        Wir haben für das Training Aufnahmen von über 300 Personen aus 108 Ortschaften in ganz Österreich verwendet:<br>
        Jeder rote Punkt auf der Karte ist eine dieser Ortschaften.<br>
    - type: volume
      id: welcome_page3
      name: <div style="font-size: 48px;"><b>Dialekterkennung mit KI</b> </div>
      content: |
        <div style="font-size: 28px;">Wenn wir der KI jetzt eine Audioaufnahme vorspielen, zeigt diese den Ort an,
        wo die Person (laut KI) herkommen könnte.<br>
        Die KI gibt ihr Bestes, aber trotzdem funktioniert die Erkennung der KI <b>nicht immer korrekt</b>.<br>
        Hier sieht man die korrekte Antwort (grüner Punkt) und die Antwort der KI (blaues Dreick):<br> </div>
      stimulus: configs/resources/audio/DialektDetect/listening_test_wavs/50618_HG_WJ_010.01_2.wav
      defaultVolume: 1.0
    - type: spatial
      id: '10612_SF_WA_553.01'
      name: <div style="font-size: 38px;"><b>Woher kommt die sprechende Person? Intro 1</b> </div>
      content: |
        <div style="font-size: 32px;">
        Klick auf <b>Start</b> und hör dir das Beispiel an. Klick auf die Karte um den blauen Punkt zu setzen!<br>
        Warst du näher dran als die KI?</div>
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/listening_test_wavs/10612_SF_WA_553.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/listening_test_wavs/10612_SF_WA_553.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    - type: spatial
      id: 61254_AI_MJ_057.01_5
      name: <div style="font-size: 40px;"><b>Woran erkennst du den Dialekt?</b> Intro 2</div>
      content: <div style="font-size: 32px;">Markiere mit den Schiebereglern unterhalb vom Audio den wichtigsten Teil!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/listening_test_wavs/61254_AI_MJ_057.01_5.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/listening_test_wavs/61254_AI_MJ_057.01_5.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None

    - type: spatial
      id: 20619_ML_WJ_493.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 1</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/20619_ML_WJ_493.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/20619_ML_WJ_493.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 50618_HG_WJ_030.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 2</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/50618_HG_WJ_030.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/50618_HG_WJ_030.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 62216_GH_WA_034.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 3</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/62216_GH_WA_034.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/62216_GH_WA_034.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 50502_LE_WA_329.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 4</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/50502_LE_WA_329.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/50502_LE_WA_329.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 41501_AD_MA_071.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 5</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/41501_AD_MA_071.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/41501_AD_MA_071.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 70706_AV_MJ_560.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 6</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/70706_AV_MJ_560.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/70706_AV_MJ_560.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 10612_SF_WA_522.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 7</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/10612_SF_WA_522.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/10612_SF_WA_522.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 80105_BR_MA_499.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 8</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/80105_BR_MA_499.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/80105_BR_MA_499.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 30501_AB_MA_039.01_3
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 9</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/30501_AB_MA_039.01_3.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/30501_AB_MA_039.01_3.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 90001_HP_MA_asterix_306
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 10</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/90001_HP_MA_asterix_306.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/90001_HP_MA_asterix_306.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: spatial
      id: 70804_BI_WA_567.01
      name: <div style="font-size: 40px;"><b>Woher kommt die sprechende Person?</b> Frage 11</div>
      content: <div style="font-size: 32px;">Hör dir das Beispiel an und klick auf die Karte.<br>Markiere den wichtigsten Teil im Audio mit den Schiebereglern!
      framerate: 5
      roomMeasurements: [600, 240, 500] # width, height, length
      showWaveform: true
      enableLooping: false
      reference: configs/resources/audio/DialektDetect/TCS_award/70804_BI_WA_567.01.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/DialektDetect/TCS_award/70804_BI_WA_567.01.wav
      responses:
        - type: localization
          name: locA
          label: A
          color: 0xff0000
          stimulus: C1
          position: [100,100,0]
          size: 10
      views: 
        - view: front
      objects: 
        - type: None
    
    - type: finish
      name: Danke fürs Mitmachen!
      content: Bitte füll den Fragebogen aus und klick auf "Ergebnisse senden".
      showResults: false
      writeResults: true
      questionnaire:
          # - type: classcode
          #   label: Klassencode
          #   name: classcode
          #   optional: true
          - type: text
            label: Vorname
            name: name
          - type: text
            label: Klasse/Gruppe/Institution
            name: class
          - type: likert
            name: gender
            label: Geschlecht
            response:
             - value: female
               label: Weiblich
             - value: male
               label: Männlich
             - value: other
               label: Divers
             - value: none
               label: Keine Angabe
          - type: number
            label: Alter
            name: age
            min: 0
            max: 100
            default: 0
          - type: text
            label: Aus welchem Bundesland kommst du?
            name: origin
            optional: true
